build:
  image: node:5.11.0
  pull: true
  commands:
    - npm update
#    - npm test


publish:
  npm:
    username: $$NPM_USERNAME
    password: $$NPM_PASSWORD
    email: $$NPM_EMAIL
    registry: https://registry.npmjs.org/
    always_auth: true


cache:
  mount:
    - node_modules
